CREATE INDEX IF NOT EXISTS "ai_chunks_document_fk_idx" ON "ai_chunks" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_documents_studio_fk_idx" ON "ai_documents" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "appointments_pack_idx" ON "appointments" USING btree ("pack_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "appointments_hold_idx" ON "appointments" USING btree ("hold_expires_at") WHERE "appointments"."payment_status" = 'pending';--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "body_metrics_studio_fk_idx" ON "body_metrics" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "checkin_assignments_due_idx" ON "checkin_assignments" USING btree ("next_due");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "checkin_assignments_form_idx" ON "checkin_assignments" USING btree ("form_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "checkin_assignments_studio_fk_idx" ON "checkin_assignments" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "checkin_forms_studio_fk_idx" ON "checkin_forms" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "checkin_responses_assignment_fk_idx" ON "checkin_responses" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "checkin_responses_studio_fk_idx" ON "checkin_responses" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_reads_user_fk_idx" ON "conversation_reads" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invites_client_idx" ON "invites" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invites_studio_fk_idx" ON "invites" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meal_checks_studio_fk_idx" ON "meal_checks" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "media_client_idx" ON "media" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "media_studio_idx" ON "media" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "messages_media_idx" ON "messages" USING btree ("media_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "metric_defs_studio_fk_idx" ON "metric_defs" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "metric_values_metric_idx" ON "metric_values" USING btree ("metric_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "metric_values_studio_fk_idx" ON "metric_values" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "password_resets_user_idx" ON "password_resets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payments_appointment_fk_idx" ON "payments" USING btree ("appointment_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payments_pack_fk_idx" ON "payments" USING btree ("pack_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "payments_price_fk_idx" ON "payments" USING btree ("price_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prices_studio_fk_idx" ON "prices" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "program_runs_program_fk_idx" ON "program_runs" USING btree ("program_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "program_runs_studio_fk_idx" ON "program_runs" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "programs_studio_fk_idx" ON "programs" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "progress_photos_studio_fk_idx" ON "progress_photos" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "push_subscriptions_user_fk_idx" ON "push_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "questionnaires_studio_fk_idx" ON "questionnaires" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reminder_log_user_fk_idx" ON "reminder_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resources_studio_idx" ON "resources" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resources_media_fk_idx" ON "resources" USING btree ("media_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_packs_studio_idx" ON "session_packs" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscriptions_price_fk_idx" ON "subscriptions" USING btree ("price_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscriptions_studio_fk_idx" ON "subscriptions" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_studio_fk_idx" ON "users" USING btree ("studio_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workouts_run_idx" ON "workouts" USING btree ("program_run_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workouts_routine_idx" ON "workouts" USING btree ("routine_id");