/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AppRouteImport } from './routes/app'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAgendaRouteImport } from './routes/app/agenda'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppComidasRouteImport } from './routes/app/comidas'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as CoachAjustesRouteImport } from './routes/coach/ajustes'
import { Route as CoachCalendarioRouteImport } from './routes/coach/calendario'
import { Route as CoachChatRouteImport } from './routes/coach/chat'
import { Route as CoachClientesRouteImport } from './routes/coach/clientes'
import { Route as AppEntrenoIndexRouteImport } from './routes/app/entreno/index'
import { Route as AppEntrenoWorkoutIdRouteImport } from './routes/app/entreno/$workoutId'
import { Route as CoachClientesIndexRouteImport } from './routes/coach/clientes/index'
import { Route as CoachClientesClientIdRouteImport } from './routes/coach/clientes/$clientId'
import { Route as CoachEntrenosIndexRouteImport } from './routes/coach/entrenos/index'
import { Route as CoachEntrenosRoutineIdRouteImport } from './routes/coach/entrenos/$routineId'
import { Route as CoachNutricionIndexRouteImport } from './routes/coach/nutricion/index'
import { Route as CoachNutricionPlanIdRouteImport } from './routes/coach/nutricion/$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppComidasRoute = AppComidasRouteImport.update({
  id: '/comidas',
  path: '/comidas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAjustesRoute = CoachAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCalendarioRoute = CoachCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => CoachRoute,
} as any)
const CoachChatRoute = CoachChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientesRoute = CoachClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CoachRoute,
} as any)
const AppEntrenoIndexRoute = AppEntrenoIndexRouteImport.update({
  id: '/entreno/',
  path: '/entreno/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenoWorkoutIdRoute = AppEntrenoWorkoutIdRouteImport.update({
  id: '/entreno/$workoutId',
  path: '/entreno/$workoutId',
  getParentRoute: () => AppRoute,
} as any)
const CoachClientesIndexRoute = CoachClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachClientesRoute,
} as any)
const CoachClientesClientIdRoute = CoachClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CoachClientesRoute,
} as any)
const CoachEntrenosIndexRoute = CoachEntrenosIndexRouteImport.update({
  id: '/entrenos/',
  path: '/entrenos/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachEntrenosRoutineIdRoute = CoachEntrenosRoutineIdRouteImport.update({
  id: '/entrenos/$routineId',
  path: '/entrenos/$routineId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachNutricionIndexRoute = CoachNutricionIndexRouteImport.update({
  id: '/nutricion/',
  path: '/nutricion/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachNutricionPlanIdRoute = CoachNutricionPlanIdRouteImport.update({
  id: '/nutricion/$planId',
  path: '/nutricion/$planId',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/instalar': typeof InstalarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/chat': typeof AppChatRoute
  '/app/comidas': typeof AppComidasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/coach/ajustes': typeof CoachAjustesRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/chat': typeof CoachChatRoute
  '/coach/clientes': typeof CoachClientesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/app/entreno/$workoutId': typeof AppEntrenoWorkoutIdRoute
  '/coach/clientes/$clientId': typeof CoachClientesClientIdRoute
  '/coach/entrenos/$routineId': typeof CoachEntrenosRoutineIdRoute
  '/coach/nutricion/$planId': typeof CoachNutricionPlanIdRoute
  '/app/entreno/': typeof AppEntrenoIndexRoute
  '/coach/clientes/': typeof CoachClientesIndexRoute
  '/coach/entrenos/': typeof CoachEntrenosIndexRoute
  '/coach/nutricion/': typeof CoachNutricionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/galeria': typeof GaleriaRoute
  '/instalar': typeof InstalarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/chat': typeof AppChatRoute
  '/app/comidas': typeof AppComidasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/coach/ajustes': typeof CoachAjustesRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/chat': typeof CoachChatRoute
  '/app': typeof AppIndexRoute
  '/coach': typeof CoachIndexRoute
  '/app/entreno/$workoutId': typeof AppEntrenoWorkoutIdRoute
  '/coach/clientes/$clientId': typeof CoachClientesClientIdRoute
  '/coach/entrenos/$routineId': typeof CoachEntrenosRoutineIdRoute
  '/coach/nutricion/$planId': typeof CoachNutricionPlanIdRoute
  '/app/entreno': typeof AppEntrenoIndexRoute
  '/coach/clientes': typeof CoachClientesIndexRoute
  '/coach/entrenos': typeof CoachEntrenosIndexRoute
  '/coach/nutricion': typeof CoachNutricionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/instalar': typeof InstalarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/chat': typeof AppChatRoute
  '/app/comidas': typeof AppComidasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/coach/ajustes': typeof CoachAjustesRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/chat': typeof CoachChatRoute
  '/coach/clientes': typeof CoachClientesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/app/entreno/$workoutId': typeof AppEntrenoWorkoutIdRoute
  '/coach/clientes/$clientId': typeof CoachClientesClientIdRoute
  '/coach/entrenos/$routineId': typeof CoachEntrenosRoutineIdRoute
  '/coach/nutricion/$planId': typeof CoachNutricionPlanIdRoute
  '/app/entreno/': typeof AppEntrenoIndexRoute
  '/coach/clientes/': typeof CoachClientesIndexRoute
  '/coach/entrenos/': typeof CoachEntrenosIndexRoute
  '/coach/nutricion/': typeof CoachNutricionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/app'
    | '/coach'
    | '/galeria'
    | '/instalar'
    | '/registro'
    | '/restablecer'
    | '/app/agenda'
    | '/app/chat'
    | '/app/comidas'
    | '/app/perfil'
    | '/coach/ajustes'
    | '/coach/calendario'
    | '/coach/chat'
    | '/coach/clientes'
    | '/app/'
    | '/coach/'
    | '/app/entreno/$workoutId'
    | '/coach/clientes/$clientId'
    | '/coach/entrenos/$routineId'
    | '/coach/nutricion/$planId'
    | '/app/entreno/'
    | '/coach/clientes/'
    | '/coach/entrenos/'
    | '/coach/nutricion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/galeria'
    | '/instalar'
    | '/registro'
    | '/restablecer'
    | '/app/agenda'
    | '/app/chat'
    | '/app/comidas'
    | '/app/perfil'
    | '/coach/ajustes'
    | '/coach/calendario'
    | '/coach/chat'
    | '/app'
    | '/coach'
    | '/app/entreno/$workoutId'
    | '/coach/clientes/$clientId'
    | '/coach/entrenos/$routineId'
    | '/coach/nutricion/$planId'
    | '/app/entreno'
    | '/coach/clientes'
    | '/coach/entrenos'
    | '/coach/nutricion'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/app'
    | '/coach'
    | '/galeria'
    | '/instalar'
    | '/registro'
    | '/restablecer'
    | '/app/agenda'
    | '/app/chat'
    | '/app/comidas'
    | '/app/perfil'
    | '/coach/ajustes'
    | '/coach/calendario'
    | '/coach/chat'
    | '/coach/clientes'
    | '/app/'
    | '/coach/'
    | '/app/entreno/$workoutId'
    | '/coach/clientes/$clientId'
    | '/coach/entrenos/$routineId'
    | '/coach/nutricion/$planId'
    | '/app/entreno/'
    | '/coach/clientes/'
    | '/coach/entrenos/'
    | '/coach/nutricion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  InstalarRoute: typeof InstalarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comidas': {
      id: '/app/comidas'
      path: '/comidas'
      fullPath: '/app/comidas'
      preLoaderRoute: typeof AppComidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/ajustes': {
      id: '/coach/ajustes'
      path: '/ajustes'
      fullPath: '/coach/ajustes'
      preLoaderRoute: typeof CoachAjustesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/calendario': {
      id: '/coach/calendario'
      path: '/calendario'
      fullPath: '/coach/calendario'
      preLoaderRoute: typeof CoachCalendarioRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/chat': {
      id: '/coach/chat'
      path: '/chat'
      fullPath: '/coach/chat'
      preLoaderRoute: typeof CoachChatRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clientes': {
      id: '/coach/clientes'
      path: '/clientes'
      fullPath: '/coach/clientes'
      preLoaderRoute: typeof CoachClientesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/app/entreno/': {
      id: '/app/entreno/'
      path: '/entreno'
      fullPath: '/app/entreno/'
      preLoaderRoute: typeof AppEntrenoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entreno/$workoutId': {
      id: '/app/entreno/$workoutId'
      path: '/entreno/$workoutId'
      fullPath: '/app/entreno/$workoutId'
      preLoaderRoute: typeof AppEntrenoWorkoutIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/coach/clientes/': {
      id: '/coach/clientes/'
      path: '/'
      fullPath: '/coach/clientes/'
      preLoaderRoute: typeof CoachClientesIndexRouteImport
      parentRoute: typeof CoachClientesRoute
    }
    '/coach/clientes/$clientId': {
      id: '/coach/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/coach/clientes/$clientId'
      preLoaderRoute: typeof CoachClientesClientIdRouteImport
      parentRoute: typeof CoachClientesRoute
    }
    '/coach/entrenos/': {
      id: '/coach/entrenos/'
      path: '/entrenos'
      fullPath: '/coach/entrenos/'
      preLoaderRoute: typeof CoachEntrenosIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/entrenos/$routineId': {
      id: '/coach/entrenos/$routineId'
      path: '/entrenos/$routineId'
      fullPath: '/coach/entrenos/$routineId'
      preLoaderRoute: typeof CoachEntrenosRoutineIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/nutricion/': {
      id: '/coach/nutricion/'
      path: '/nutricion'
      fullPath: '/coach/nutricion/'
      preLoaderRoute: typeof CoachNutricionIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/nutricion/$planId': {
      id: '/coach/nutricion/$planId'
      path: '/nutricion/$planId'
      fullPath: '/coach/nutricion/$planId'
      preLoaderRoute: typeof CoachNutricionPlanIdRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppChatRoute: typeof AppChatRoute
  AppComidasRoute: typeof AppComidasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntrenoWorkoutIdRoute: typeof AppEntrenoWorkoutIdRoute
  AppEntrenoIndexRoute: typeof AppEntrenoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppChatRoute: AppChatRoute,
  AppComidasRoute: AppComidasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntrenoWorkoutIdRoute: AppEntrenoWorkoutIdRoute,
  AppEntrenoIndexRoute: AppEntrenoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachClientesRouteChildren {
  CoachClientesClientIdRoute: typeof CoachClientesClientIdRoute
  CoachClientesIndexRoute: typeof CoachClientesIndexRoute
}

const CoachClientesRouteChildren: CoachClientesRouteChildren = {
  CoachClientesClientIdRoute: CoachClientesClientIdRoute,
  CoachClientesIndexRoute: CoachClientesIndexRoute,
}

const CoachClientesRouteWithChildren = CoachClientesRoute._addFileChildren(
  CoachClientesRouteChildren,
)

interface CoachRouteChildren {
  CoachAjustesRoute: typeof CoachAjustesRoute
  CoachCalendarioRoute: typeof CoachCalendarioRoute
  CoachChatRoute: typeof CoachChatRoute
  CoachClientesRoute: typeof CoachClientesRouteWithChildren
  CoachIndexRoute: typeof CoachIndexRoute
  CoachEntrenosRoutineIdRoute: typeof CoachEntrenosRoutineIdRoute
  CoachNutricionPlanIdRoute: typeof CoachNutricionPlanIdRoute
  CoachEntrenosIndexRoute: typeof CoachEntrenosIndexRoute
  CoachNutricionIndexRoute: typeof CoachNutricionIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachAjustesRoute: CoachAjustesRoute,
  CoachCalendarioRoute: CoachCalendarioRoute,
  CoachChatRoute: CoachChatRoute,
  CoachClientesRoute: CoachClientesRouteWithChildren,
  CoachIndexRoute: CoachIndexRoute,
  CoachEntrenosRoutineIdRoute: CoachEntrenosRoutineIdRoute,
  CoachNutricionPlanIdRoute: CoachNutricionPlanIdRoute,
  CoachEntrenosIndexRoute: CoachEntrenosIndexRoute,
  CoachNutricionIndexRoute: CoachNutricionIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  InstalarRoute: InstalarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
