/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AppRouteImport } from './routes/app'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppComidasRouteImport } from './routes/app/comidas'
import { Route as AppEntrenoRouteImport } from './routes/app/entreno'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as CoachAjustesRouteImport } from './routes/coach/ajustes'
import { Route as CoachCalendarioRouteImport } from './routes/coach/calendario'
import { Route as CoachChatRouteImport } from './routes/coach/chat'
import { Route as CoachEntrenosRouteImport } from './routes/coach/entrenos'
import { Route as CoachNutricionRouteImport } from './routes/coach/nutricion'
import { Route as CoachClientesIndexRouteImport } from './routes/coach/clientes/index'
import { Route as CoachClientesClientIdRouteImport } from './routes/coach/clientes/$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppComidasRoute = AppComidasRouteImport.update({
  id: '/comidas',
  path: '/comidas',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrenoRoute = AppEntrenoRouteImport.update({
  id: '/entreno',
  path: '/entreno',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAjustesRoute = CoachAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCalendarioRoute = CoachCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => CoachRoute,
} as any)
const CoachChatRoute = CoachChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CoachRoute,
} as any)
const CoachEntrenosRoute = CoachEntrenosRouteImport.update({
  id: '/entrenos',
  path: '/entrenos',
  getParentRoute: () => CoachRoute,
} as any)
const CoachNutricionRoute = CoachNutricionRouteImport.update({
  id: '/nutricion',
  path: '/nutricion',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientesIndexRoute = CoachClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientesClientIdRoute = CoachClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/instalar': typeof InstalarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/app/chat': typeof AppChatRoute
  '/app/comidas': typeof AppComidasRoute
  '/app/entreno': typeof AppEntrenoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/coach/ajustes': typeof CoachAjustesRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/chat': typeof CoachChatRoute
  '/coach/entrenos': typeof CoachEntrenosRoute
  '/coach/nutricion': typeof CoachNutricionRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/clientes/$clientId': typeof CoachClientesClientIdRoute
  '/coach/clientes/': typeof CoachClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/galeria': typeof GaleriaRoute
  '/instalar': typeof InstalarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/app/chat': typeof AppChatRoute
  '/app/comidas': typeof AppComidasRoute
  '/app/entreno': typeof AppEntrenoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/coach/ajustes': typeof CoachAjustesRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/chat': typeof CoachChatRoute
  '/coach/entrenos': typeof CoachEntrenosRoute
  '/coach/nutricion': typeof CoachNutricionRoute
  '/app': typeof AppIndexRoute
  '/coach': typeof CoachIndexRoute
  '/coach/clientes/$clientId': typeof CoachClientesClientIdRoute
  '/coach/clientes': typeof CoachClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/app': typeof AppRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/instalar': typeof InstalarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/app/chat': typeof AppChatRoute
  '/app/comidas': typeof AppComidasRoute
  '/app/entreno': typeof AppEntrenoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/coach/ajustes': typeof CoachAjustesRoute
  '/coach/calendario': typeof CoachCalendarioRoute
  '/coach/chat': typeof CoachChatRoute
  '/coach/entrenos': typeof CoachEntrenosRoute
  '/coach/nutricion': typeof CoachNutricionRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/clientes/$clientId': typeof CoachClientesClientIdRoute
  '/coach/clientes/': typeof CoachClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/app'
    | '/coach'
    | '/galeria'
    | '/instalar'
    | '/registro'
    | '/restablecer'
    | '/app/chat'
    | '/app/comidas'
    | '/app/entreno'
    | '/app/perfil'
    | '/coach/ajustes'
    | '/coach/calendario'
    | '/coach/chat'
    | '/coach/entrenos'
    | '/coach/nutricion'
    | '/app/'
    | '/coach/'
    | '/coach/clientes/$clientId'
    | '/coach/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/galeria'
    | '/instalar'
    | '/registro'
    | '/restablecer'
    | '/app/chat'
    | '/app/comidas'
    | '/app/entreno'
    | '/app/perfil'
    | '/coach/ajustes'
    | '/coach/calendario'
    | '/coach/chat'
    | '/coach/entrenos'
    | '/coach/nutricion'
    | '/app'
    | '/coach'
    | '/coach/clientes/$clientId'
    | '/coach/clientes'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/app'
    | '/coach'
    | '/galeria'
    | '/instalar'
    | '/registro'
    | '/restablecer'
    | '/app/chat'
    | '/app/comidas'
    | '/app/entreno'
    | '/app/perfil'
    | '/coach/ajustes'
    | '/coach/calendario'
    | '/coach/chat'
    | '/coach/entrenos'
    | '/coach/nutricion'
    | '/app/'
    | '/coach/'
    | '/coach/clientes/$clientId'
    | '/coach/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  AppRoute: typeof AppRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  InstalarRoute: typeof InstalarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comidas': {
      id: '/app/comidas'
      path: '/comidas'
      fullPath: '/app/comidas'
      preLoaderRoute: typeof AppComidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entreno': {
      id: '/app/entreno'
      path: '/entreno'
      fullPath: '/app/entreno'
      preLoaderRoute: typeof AppEntrenoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/ajustes': {
      id: '/coach/ajustes'
      path: '/ajustes'
      fullPath: '/coach/ajustes'
      preLoaderRoute: typeof CoachAjustesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/calendario': {
      id: '/coach/calendario'
      path: '/calendario'
      fullPath: '/coach/calendario'
      preLoaderRoute: typeof CoachCalendarioRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/chat': {
      id: '/coach/chat'
      path: '/chat'
      fullPath: '/coach/chat'
      preLoaderRoute: typeof CoachChatRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/entrenos': {
      id: '/coach/entrenos'
      path: '/entrenos'
      fullPath: '/coach/entrenos'
      preLoaderRoute: typeof CoachEntrenosRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/nutricion': {
      id: '/coach/nutricion'
      path: '/nutricion'
      fullPath: '/coach/nutricion'
      preLoaderRoute: typeof CoachNutricionRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clientes/': {
      id: '/coach/clientes/'
      path: '/clientes'
      fullPath: '/coach/clientes/'
      preLoaderRoute: typeof CoachClientesIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clientes/$clientId': {
      id: '/coach/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/coach/clientes/$clientId'
      preLoaderRoute: typeof CoachClientesClientIdRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppComidasRoute: typeof AppComidasRoute
  AppEntrenoRoute: typeof AppEntrenoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppComidasRoute: AppComidasRoute,
  AppEntrenoRoute: AppEntrenoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachRouteChildren {
  CoachAjustesRoute: typeof CoachAjustesRoute
  CoachCalendarioRoute: typeof CoachCalendarioRoute
  CoachChatRoute: typeof CoachChatRoute
  CoachEntrenosRoute: typeof CoachEntrenosRoute
  CoachNutricionRoute: typeof CoachNutricionRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachClientesClientIdRoute: typeof CoachClientesClientIdRoute
  CoachClientesIndexRoute: typeof CoachClientesIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachAjustesRoute: CoachAjustesRoute,
  CoachCalendarioRoute: CoachCalendarioRoute,
  CoachChatRoute: CoachChatRoute,
  CoachEntrenosRoute: CoachEntrenosRoute,
  CoachNutricionRoute: CoachNutricionRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachClientesClientIdRoute: CoachClientesClientIdRoute,
  CoachClientesIndexRoute: CoachClientesIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  AppRoute: AppRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  InstalarRoute: InstalarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
